Tugas_PPW_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import fitur_homepage.urls as homepage
import fitur_login.urls as login
import fitur_dashboard.urls as dashboard
import fitur_history.urls as history
import fitur_profile.urls as profile
import fitur_status.urls as status
import fitur_friend.urls as friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(homepage,namespace='index')),
    url(r'^login/', include(login,namespace='login')),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^riwayat/', include(history, namespace='history')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^friend/', include(friend, namespace='friend')),
]

fitur_login/urls.py
from django.conf.urls import url
from utils.custom_auth import auth_login, auth_logout

from .views import index
urlpatterns = [
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

fitur_login/models.py
from django.db import models

# Create your models here.

fitur_login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# NOTE : untuk membantu dalam memahami tujuan dari suatu fungsi (def)
# Silahkan jelaskan menggunakan bahasa kalian masing-masing, di bagian atas
# sebelum fungsi tersebut.

def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect('/dashboard/')
    else:
        html = 'layout/login.html'
        return render(request, html)

fitur_login/templates/layout/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 9">
    <meta name="author" content="{{author}}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_login.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <title>
        Login page
    </title>
</head>
<body style="background-color:#49807D;">
  <br>
  <br>
  <br>
  <br><br>
  <br>
  <br>
  <br><br>
  <br><br>
  <br><br>
  <br>
  <form action="{% url 'login:auth_login' %}" method="POST">
    {% csrf_token %}
    <h2><span class="entypo-login"></span> Login</h2>
    <button class="submit"><span class="entypo-lock"></span></button>
    <span class="entypo-user inputUserIcon"></span>
    <input type="text" class="user" id="username" name="username" required placeholder="username"/>
    <span class="entypo-key inputPassIcon"></span>
    <input type="password" id="password" name="password" required class="pass"placeholder="password"/>
  </form>


<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/fitur_login.js' %}" ></script>
</body>
</html>