Tugas_PPW_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import fitur_homepage.urls as homepage
import fitur_login.urls as login
import fitur_dashboard.urls as dashboard
import fitur_history.urls as history
import fitur_profile.urls as profile
import fitur_status.urls as status
import fitur_friend.urls as friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(homepage,namespace='index')),
    url(r'^login/', include(login,namespace='login')),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^riwayat/', include(history, namespace='history')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^friend/', include(friend, namespace='friend')),
]

fitur_status/urls.py
from django.conf.urls import url
from .views import index, index2, add_status, delete_status
from django.conf.urls import url, include

#url formar app
urlpatterns = [
	url(r'^$', index, name='index'),
    url(r'^(?P<npm>[0-9]+)/$', index2, name='index2'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status', delete_status, name='delete_status'),
]

fitur_status/models.py
from django.db import models

class Status(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'cols': 60,
        'rows': 3,
        'class': 'status-form-textarea',
        'placeholder':'...',
        'max_length' : 500,
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

fitur_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from fitur_profile.models import Mahasiswa
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):#pragma: no cover
    print("#==> masuk index")
    if 'user_login' in request.session:
        npm = request.session['kode_identitas']
        return HttpResponseRedirect('/status/'+npm)
    else:
        return HttpResponseRedirect('/')

def index2(request, npm):#pragma: no cover
    if 'user_login' in request.session:
        status_id = request.get_full_path().split("/")[-2]

        status = Status.objects.all()[::-1]
        profile = Mahasiswa.objects.get(pk=1)

        response['profile'] = profile
        response['status'] = status
        response['mhs_name'] = request.session['name']
        response['latest'] = Status.objects.last()
        response['verified'] = False
        if npm == status_id:
            response['status_form'] = Status_Form
            response['verified'] = True

        html = 'fitur_status/status.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')

def add_status(request):#pragma: no cover
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def delete_status(request):#pragma: no cover
    status = Status.objects.get(id=int(request.POST.get("id-value", "")))
    status.delete()
    return HttpResponseRedirect('/status/')

fitur_status/templates/fitur_status/status.html
{% extends "fitur_status/layout/base.html" %}
{% block content_status %}
	<div>
		<form id="form" method="POST" action="{% url 'status:add_status' %}">
			{% csrf_token %}
			{{ status_form }}
        	<br>
        	{% if verified %}
				<button type="submit" id="post">Post</button>
			{% endif %}
	</form>
	</div>
	<br>
	<div class="container" style="overflow-y: scroll; height: 100px; width: 100%;">
		{% for data in status %}
        <div id="date-added" class="status-list-date-added">
        	{{ data.created_date.date|date:"d F Y" }}
    	</div>
    	<div class="status-list-description">
        	{{data.description}}
        </div>
        <div class="to-do-list-delete">
            <div class="to-do-list-delete-button">
                <form method="POST" action="{% url 'status:delete_status' %}">
                	{% csrf_token %}
                	<button id="delete-button" type="submit" value="{{data.id}}" name="id-value">Delete</button>
            	</form>
        	</div>
        </div>

    	<br>
		{% endfor %}
	</div>
{% endblock %}