Tugas_PPW_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import fitur_homepage.urls as homepage
import fitur_login.urls as login
import fitur_dashboard.urls as dashboard
import fitur_history.urls as history
import fitur_profile.urls as profile
import fitur_status.urls as status
import fitur_friend.urls as friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(homepage,namespace='index')),
    url(r'^login/', include(login,namespace='login')),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^riwayat/', include(history, namespace='history')),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^friend/', include(friend, namespace='friend')),
]

fitur_login/urls.py
from django.conf.urls import url
from utils.custom_auth import auth_login, auth_logout

from .views import index
urlpatterns = [
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

fitur_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, add_expertise, delete_expertise, update_profile, save_data, cancel_save_data

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^update-profile/$', update_profile, name='update–profile'),
	url(r'^add-expertise/$', add_expertise, name='add-expertise'),
	url(r'^delete-expertise/(?P<expertise_id>[0-9]+)/$', delete_expertise, name='delete-expertise'),
	url(r'^save-data/$', save_data, name='save-data'),
	url(r'^cancel-save-data/$', cancel_save_data, name='cancel-save-data'),
]

fitur_profile/models.py
from django.db import models
# Create your models here.

class Mahasiswa(models.Model):
	name = models.CharField(max_length=50, default="")
	birth_date = models.DateField(default="2017-01-01")
	username = models.CharField(max_length=50, default="")
	npm = models.IntegerField()
	angkatan = models.IntegerField()
	gender = models.CharField(max_length=10, default="")
	email = models.EmailField(max_length=70, default="")
	profile_linkedin = models.CharField(max_length=70, default="")
	photo = models.URLField(default="https://www.vccircle.com/wp-content/uploads/2017/03/default-profile.png")
	show_grade = models.BooleanField(default=False)
	last_post = models.CharField(max_length=140, default="")
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
 		return self.name + ' ' + str(self.npm)


class Expertise(models.Model):
	name = models.CharField(max_length=20, default="")
	level = models.CharField(max_length=20, default="")
	mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE, related_name='expertises')

	def __str__(self):
 		return self.name + ' from ' + self.mahasiswa.name

class Post(models.Model):
	message = models.CharField(max_length=140, default="")
	created_date = models.DateTimeField(auto_now_add=True)
	mahasiswa = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE, related_name='posts')

fitur_profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from .models import Mahasiswa, Expertise
from django.views.decorators.csrf import csrf_exempt
from fitur_status.models import Status

def index(request):
	print ("#==> masuk index")
	if 'user_login' in request.session:
		mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
		expertises = Expertise.objects.filter(mahasiswa = mahasiswa)

		response = {'mahasiswa' : mahasiswa}
		response['mhs_name'] = request.session['name']
		response['expertises'] = expertises
		response['latest'] = Status.objects.last()
		response['status'] = Status.objects.all()

		html = 'fitur_profile/profile.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect('/')

def edit_profile(request):
	if 'user_login' in request.session:
		html = 'fitur_profile/edit_profile.html'
		mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
		print(mahasiswa.photo)
		expertises = Expertise.objects.filter(mahasiswa = mahasiswa)
		# for expertise in expertises:
		# 	print(expertise.name, expertise.mahasiswa.name)
		response = {"npm" : request.session['kode_identitas']}
		response['expertises'] = expertises
		response['mahasiswa'] = mahasiswa
		return render(request, html, response)
	else:
		return HttpResponseRedirect('/')

@csrf_exempt
def add_expertise(request):
	if request.method == 'POST':
		new_expertise = request.POST.get('new_expertise', False)
		level = request.POST.get('level', False)
		mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
		if (not is_expertise_taken(new_expertise, mahasiswa)):
			expertise = Expertise(name=new_expertise, level=level, mahasiswa= mahasiswa)
			expertise.save()
			data = model_to_dict(expertise)
			return JsonResponse(data)
		return JsonResponse({'message': 'keahlian sudah ditambahkan'}, status=400)

def is_expertise_taken(name, mahasiswa):
	return (Expertise.objects.filter(name=name, mahasiswa=mahasiswa).count() != 0)

@csrf_exempt
def delete_expertise(request, expertise_id):
	Expertise.objects.filter(id=expertise_id).delete()
	return JsonResponse({'message': 'expertise dihapus dari daftar expertise'}, status=204)

@csrf_exempt
def update_profile(request):
	if request.method == 'POST':
		mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
		first_name = request.POST.get('first_name', False)
		last_name = request.POST.get('last_name', False)
		mahasiswa.name = first_name + " " + last_name
		mahasiswa.photo = request.POST.get('photo', False)
		mahasiswa.email = request.POST.get('email', False)
		mahasiswa.profile_linkedin = request.POST.get('profile_linkedin', False)
		mahasiswa.save()
		data = model_to_dict(mahasiswa)
		return JsonResponse(data)
	return JsonResponse({'message' : 'mahasiswa sudah punya data'}, status=400)

@csrf_exempt
def save_data(request):
	if request.method == 'POST':
		mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
		mahasiswa.show_grade = request.POST.get('show_grade', False)
		mahasiswa.save()
		html = 'fitur_profile/profile.html'
		return render(request, html, response)
	return JsonResponse({'message' : 'mahasiswa gagal save data'}, status=400)

@csrf_exempt
def cancel_save_data(request):
	mahasiswa = Mahasiswa.objects.get(npm = request.session['kode_identitas'])
	Expertise.objects.filter(mahasiswa = mahasiswa).delete()
	html = 'fitur_profile/profile.html'
	return render(request, html, response)

fitur_profile/templates/fitur_profile/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="LAB 7">
  <meta name="author" content="{{author}}">
  <!-- bootstrap csss -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_dashboard.css' %}" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="css/style.css">
</head>
<div class="topleft">
  Selamat Datang, {{mahasiswa.name}}!
</div>
<div class="toprightaside">
  User<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Happy_Human.svg/157px-Happy_Human.svg.png" alt="Smiley face" height="42" width="22">
</div><a href="{% url 'login:auth_logout' %}" class="btn btn-danger pull-right topright" onclick="return confirm('Keluar?')">Logout</a>
<body align="left">
  <div id="wrapper">
    <div id="profile">
      <div class="img src="https://i2.wp.com/www.acehtrend.co/wp-content/uploads/2016/03/monyet.jpg?fit=1200%2C800""></div>
      <a href="http://kaskus.co.id/" class="btn btn_left">Lihat Forum</a>
      <a href="https://www.facebook.com/CaptainJackSparrow" class="btn btn_right">Edit Profile</a>
      <div class="info">
        <strong>Jumlah Status: </strong> {{status|length}}
        <br>
        <strong>Status Terakhir: {{latest.description}}</strong>
      </div>
    </div>

  <content>
    <section class="page">
    <section>
      <ul class="tabs-controls">
        <li class="tabs-controls__item">
          <a href="#" class="tabs-controls__link" data-id="1">
            Home
          </a>
        </li>
        <li class="tabs-controls__item">
          <a href="#" class="tabs-controls__link tabs-controls__link--active" data-id="2">
            Profil
          </a>
        </li>
        <li class="tabs-controls__item">
          <a href="#" class="tabs-controls__link" data-id="3">
            Riwayat
          </a>
        </li>
        <li class="tabs-controls__item">
          <a href="#" class="tabs-controls__link" data-id="4">
            Status
          </a>
        </li>
        <li class="tabs-controls__item">
          <a href="#" class="tabs-controls__link" data-id="5">
            Teman
          </a>
        </li>
        
      </ul>
    </section>
    <section class="cards-container">
      <div class="card" id="1">
        <h1>B. Elit, sed do eiusmod</h1>
        <p>
          Elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
        </p>
        
      </div>
      <div class="card card--current" id="2">
        <form id="fields-edit-profile" action="#">
          {% csrf_token %}
          <button type="submit">edit profile</button>
        </form>

        {% block content_profile %}
               <!-- content goes here -->
        {% endblock %}
      </div>
      <div class="card" id="3">
        <h1>C. Consectetur adipisicing elit</h1>
        <p>
          Consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
        </p>
      </div>
      <div class="card" id="4">
        <h1>D. Sed do eiusmod</h1>
        <p>
          Sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrcaecat cupidatat nonv proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
      <div class="card" id="5">
        <h1>E. Ut enim ad minim veniam</h1>
        <p>
          Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in vo cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
      
    </section>
  </section>
  </content>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'js/fitur_dashboard.js' %}" ></script>
  <script type="text/javascript">
      $("#fields-edit-profile").on("submit", function () {
        window.open('/profile/edit/');
        event.preventDefault();
        });  
      </script>
</body>
</html>